### ISSUE TITLE
OSX version? :)

### ISSUE THREAD

**Issue by toorshia** [Xonshiz/ReadComicOnline-Downloader#1]
What about us, poor OSX users? Could you pack this up to use on Mac? Thanks :)

**Comment by Xonshiz** [comment]
Sorry, I don't really have an OSX to compile this python file. If you're interested, install python and pyinstaller on your OS X and get back to me. I'll tell you procedure for, shouldn't be a problem

**Comment by ghost** [comment]
It worked on my OS X install. You can just run the python file from terminal and place/install it's depends. It will error and tell you what you need to get on first run.

**Comment by toorshia** [comment]
I actually tried that first, installed python and ran .py file, but after receiving errors, and understanding phantomjs is required, but came in an .exe, I just ran away scared :D
I will try working my way trough it tonight, and come back here to cry for help if needed.
Thnaks guys!

**Comment by ghost** [comment]
Phantomjs has a Mac build, just place it's binary in /usr/bin

**Comment by toorshia** [comment]
Got it working! Thanks guys! :)
