### ISSUE TITLE
Any chance of shorter folder names?

### ISSUE THREAD

**Issue by Efreak** [Xonshiz/ReadComicOnline-Downloader#3]
Perhaps prompt the user for folder names and whether or not to use generated folder names or simply numeric folder names (I just use numbers, zip it up, and rename to cbz). The current generated folder names are awfully long, and it's putting only a single folder into a subfolder on some of them. I'm not sure if this is specific to sunstone, or if it's a general issue with RCO. There's also a doubled space near the end.

This is more of an annoyance than a problem.

```
[@:~/comix] $ find|grep Sunstone
./Sunstone TPB 3 comic online - Sunstone TPB 3
./Sunstone TPB 3 comic online - Sunstone TPB 3/Issue Sunstone TPB 3 comic online download Sunstone TPB 3  Sunstone TPB 3
./Sunstone TPB 4 comic online - Sunstone TPB 4
./Sunstone TPB 4 comic online - Sunstone TPB 4/Issue Sunstone TPB 4 comic online download Sunstone TPB 4  Sunstone TPB 4
./Sunstone TPB 2 comic online - Sunstone TPB 2
./Sunstone TPB 2 comic online - Sunstone TPB 2/Issue Sunstone TPB 2 comic online download Sunstone TPB 2  Sunstone TPB 2
./Sunstone TPB 1 comic online - Sunstone TPB 1
./Sunstone TPB 1 comic online - Sunstone TPB 1/Issue Sunstone TPB 1 comic online download Sunstone TPB 1  Sunstone TPB 1
```

**Comment by Xonshiz** [comment]
I'll look into the issue :)
