### ISSUE TITLE
[FIXED] Range Download only does 1st chapter

### ISSUE THREAD

**Issue by maphie14** [Xonshiz/ReadComicOnline-Downloader#4]
Range download only does the 1st chapter of those in range. ex. 15-27 it only does 15 then it exits.

When you select range as All it works fine. I wonder can you help me.

Btw thanks for the script. Its awesome

[ghostdriver&single_exception.zip](https://github.com/Xonshiz/ReadComicOnline-Downloader/files/561073/ghostdriver.single_exception.zip)

**Comment by Xonshiz** [comment]
Thanks for reporting it. I've checked it on my end and this is kind of annoying. I'll release the fix in a few hours/minutes.

**Comment by Xonshiz** [comment]
Updated and fixed. Please feel free to re-open, if the the issue persists.
