### ISSUE TITLE
"Browser not supported" reCAPTCHA Exception

### ISSUE THREAD

**Issue by dubsand** [Xonshiz/ReadComicOnline-Downloader#6]
## Issue:
Using the Windows binary, comics cant be downloaded from http://readcomiconline.to/ due to reCAPTCHA not being passed. According to the exception screenshot, a supported browser is needed to receive a captcha. This was probably broken just a day/few hours ago since I used it successfully 3 days earlier. Also probably affects your other project at https://github.com/Xonshiz/comic-dl .

<img src="http://i.imgur.com/cGtTYql.png" width="480">

## Reproducing the issue:

Just paste any link into the command line while running the script (e.g. http://readcomiconline.to/Comic/The-New-Mutants/) and enter range/issues. Issues will not be downloaded as every issue yields the reCAPTCHA exception seen above. Tested with multiple links.

**Comment by Xonshiz** [comment]
Hello, this project is no more supported. Please check out [comic-dl](https://github.com/Xonshiz/comic-dl) for this. It's faster and better than this and it supports more websites as well.
