### ISSUE TITLE
Not Downloading anything

### ISSUE THREAD

**Issue by Krishnarohith10** [Xonshiz/ReadComicOnline-Downloader#8]
Hello, first thank you for this because I am DC Comics fanboy but don't know how to download, also fed up with online reading so, find your link to download and appreciate it.

Now Coming to issue, I have download few comics as soon as I got this website but then after few downloading then I am getting this for every link comic book I want to download here's a snap
![1](https://user-images.githubusercontent.com/44919399/80591899-1f898b00-8a3c-11ea-9fd0-93424f378783.png)

please help me with this issue. Thank You.

**Comment by Aemilian666** [comment]
Sorry, bud. THey no longer give a shit about this program. They prefer to create more complicated ones instead/
